blogs/urls.py
from django.urls import path

from blogs.apps import BlogsConfig
from blogs.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView

app_name = BlogsConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import HomePageView, MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, \
    MailingDeleteView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, \
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView

app_name = MainConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('mailings/', MailingListView.as_view(), name='mailings'),
    path('mailings/<int:pk>', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailings/update/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailings/delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),
    path('clients/', ClientListView.as_view(), name='clients'),
    path('clients/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('messages/', MessageListView.as_view(), name='messages'),
    path('messages/<int:pk>', MessageDetailView.as_view(), name='message_detail'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('messages/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
]

blogs/models.py
from django.db import models

from config.settings import AUTH_USER_MODEL

# Create your models here.
NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    body = models.TextField(max_length=300, verbose_name="Содержимое")
    image = models.ImageField(upload_to='blogs/', verbose_name="Изображение", **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    view_count = models.IntegerField(default=0, verbose_name="Кол-во просмотров")
    is_published = models.BooleanField(default=False, verbose_name="Статус публикации")
    owner = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name="Владелец", **NULLABLE)

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"

blogs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blogs.models import Blog


# Create your views here.
class BlogListView(ListView):
    model = Blog


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object()
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ['title', 'body', 'image']
    success_url = reverse_lazy('blogs:blog_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        context = self.get_context_data()

        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = "__all__"
    success_url = reverse_lazy('blogs:blog_list')


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blogs:blog_list')

blogs/templates/blogs/blog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
  <div class="col-12">
    <div class="row">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <p>Хотите удалить блог "{{object.title}}"?</p>
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'blogs:blog_list' %}" class="btn btn-outline-primary">Отмена</a>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blogs/templates/blogs/blog_detail.html
{% extends 'main/base.html' %}
{% load filters %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{object.title}}</h1>
</div>
<div class="row text-start">
    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <img src="{{object.image|my_media}}"
                 width="350"
                 height="350">
            <div class="card-header">{{object.title}}</div>
            <div class="card-body">{{object.body}}</div>
            <div class="card-header">Информация:</div>
            <div class="card-body">
              <div class="list-footer-display">
                <li>Дата публикации: {{object.created_at}}</li>
                <li>Кол-во просмотров: {{object.view_count}}</li>
              </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/blog_form.html
{% extends 'main/base.html' %}

{% block content %}
  <div class="col-12">
    <div class="row">
      <div class="card">
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">
              {% if object %}
                Изменить
              {% else %}
                Создать
              {% endif %}
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blogs/templates/blogs/blog_list.html
{% extends 'main/base.html' %}
{% load filters %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Наш и Ваш Блог</h1>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blogs:blog_create' %}">Написать статью</a>
</div>
<div class="row text-center">
    {% for object in object_list %}
    {% if object.is_published or perms.main.set_active %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img src="{{object.image|my_media}}"
                     width="350"
                     height="350">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.title}}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Просмотры: {{object.view_count}}</li>
                        {% if perms.main.set_active %}
                        <li>
                            Статус публикации: {% if object.is_published %} Опубликовано {% else %} Ожидает модерации {% endif %}
                        </li>
                        {% endif %}
                    </ul>
                    <a href="{% url 'blogs:blog_detail' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Почитать</a>
                    {% if perms.main.set_active or object.owner == user %}
                    <a href="{% url 'blogs:blog_update' object.pk %}" class="btn btn-lg btn-block btn-primary">Изменить</a>
                    <a href="{% url 'blogs:blog_delete' object.pk %}" class="btn btn-lg btn-block btn-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}