config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import HomePageView, MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, \
    MailingDeleteView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, \
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView

app_name = MainConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('mailings/', MailingListView.as_view(), name='mailings'),
    path('mailings/<int:pk>', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailings/update/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailings/delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),
    path('clients/', ClientListView.as_view(), name='clients'),
    path('clients/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('messages/', MessageListView.as_view(), name='messages'),
    path('messages/<int:pk>', MessageDetailView.as_view(), name='message_detail'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('messages/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, RegisterView, ProfileView, verify_user, UsersListView, UserManagerView

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('users/', UsersListView.as_view(), name='users_list'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('register/confirm/<str:verify_code>/', verify_user, name='verify_user'),
    path('manage/<int:pk>', UserManagerView.as_view(), name='manage'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    verification_code = models.CharField(max_length=20, verbose_name="Ключ верификации", **NULLABLE)
    is_active = models.BooleanField(default=False, verbose_name="Статус пользователя")
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("set_active", "Can change is_active field"),
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2",)


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email", "first_name", "last_name")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.contrib.auth.views import LoginView as BaseLoginView
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


# Create your views here.


class UsersListView(ListView):
    model = User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        verify_code = ''.join([str(random.randint(0, 9)) for i in range(6)])
        user.verification_code = verify_code
        user.save()
        link = f"http://{self.request.get_host()}/users/register/confirm/{verify_code}/"
        message = f"Для подтверждения регистрации перейдите по ссылке: {link}"
        send_mail(
            "Регистрация",
            message,
            EMAIL_HOST_USER,
            [user.email],
            False
        )

        return super().form_valid(form)


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('main:index')

    def get_object(self, queryset=None):
        return self.request.user


def verify_user(request, verify_code):
    for user in User.objects.all():
        if user.verification_code == verify_code:
            user.is_active = True
            user.save()
    return redirect(reverse_lazy('users:login'))


class LoginView(BaseLoginView):
    template_name = 'users/login.html'

    def get_success_url(self):
        return reverse_lazy('main:index')


class UserManagerView(UpdateView):
    model = User
    fields = ['is_active', ]
    success_url = reverse_lazy('users:users_list')

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content %}
  <div class="col-12">
    <form method="post" action="" enctype="multipart/form-data">
      <div class="row">
          <div class="col-4"></div>
        <div class="col-4">
          <div class="card">
              <div class="card-header">
                  <h3 class="card-title">Вход</h3>
              </div>
            <div class="card-body">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Войти</button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}

{% block content %}
  <div class="col-12">
    <form method="post" enctype="multipart/form-data">
      <div class="row">
          <div class="col-4"></div>
        <div class="col-4">
          <div class="card">
              <div class="card-header">
                  <h3 class="card-title">Регистрация</h3>
              </div>
            <div class="card-body">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
  <div class="col-12">
    <form method="post" enctype="multipart/form-data">
      <div class="row">
          <div class="col-4"></div>
        <div class="col-4">
          <div class="card">
              <div class="card-header">
                  <h3 class="card-title">Профиль</h3>
              </div>
            <div class="card-body">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-left">
    <h1 class="display-4">Пользователи</h1>
</div>
<div class="row text-center">
    {% for object in object_list %}
    {% if not object.is_staff %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.email }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Имя: {{ object.first_name }}</li>
                        <li>Фамилия: {{ object.last_name }}</li>
                    </ul>
                    <a href="{% url 'users:manage' object.pk %}" class="btn btn-lg btn-block btn-primary">Изменить</a>
                </div>

            </div>
        </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}