blogs/urls.py
from django.urls import path

from blogs.apps import BlogsConfig
from blogs.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView

app_name = BlogsConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import HomePageView, MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, \
    MailingDeleteView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, \
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView

app_name = MainConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('mailings/', MailingListView.as_view(), name='mailings'),
    path('mailings/<int:pk>', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailings/update/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailings/delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),
    path('clients/', ClientListView.as_view(), name='clients'),
    path('clients/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('messages/', MessageListView.as_view(), name='messages'),
    path('messages/<int:pk>', MessageDetailView.as_view(), name='message_detail'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('messages/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
]

main/models.py
import datetime

import pytz
from django.conf import settings
from django.db import models

from config.settings import AUTH_USER_MODEL

# Create your models here.

NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    email = models.EmailField(verbose_name="контактная почта", **NULLABLE)
    full_name = models.CharField(max_length=150, verbose_name="ФИО")
    comment = models.CharField(max_length=150, verbose_name="Комментарий", **NULLABLE)
    owner = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name="Владелец", **NULLABLE)

    def __str__(self):
        return f"ФИО: {self.full_name}, Email: {self.email}"

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Message(models.Model):
    header = models.CharField(max_length=150, verbose_name="Заголовок")
    body = models.TextField(verbose_name="Текст сообщения")
    owner = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name="Владелец", **NULLABLE)

    def __str__(self):
        return self.header

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"


class Mailing(models.Model):
    zone = pytz.timezone(settings.TIME_ZONE)
    current_time = datetime.datetime.now(zone)
    name = models.CharField(max_length=100, verbose_name="Название рассылки", **NULLABLE)
    date_time = models.DateTimeField(default=current_time, verbose_name="Дата и время первой рассылки")
    period_choices = {"День": "day", "Неделя": "week", "Месяц": "month"}
    period = models.CharField(max_length=30, choices=period_choices, default="День", verbose_name="периодичность")
    status_choices = {"Создана": "created", "Выполняется": "ongoing", "Завершена": "finished"}
    status = models.CharField(max_length=30, choices=status_choices, default="Создана", verbose_name="статус рассылки")
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name="сообщение", **NULLABLE)
    clients = models.ManyToManyField(Client, verbose_name="Клиенты", **NULLABLE)
    start = models.DateTimeField(default=current_time, verbose_name="дата и время начала")
    finish = models.DateTimeField(default=current_time + datetime.timedelta(days=30),
                                  verbose_name="дата и время окончания")
    is_active = models.BooleanField(default=False, verbose_name="активность")
    owner = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name="Владелец", **NULLABLE)
    next_sending_time = models.DateTimeField(verbose_name="Время следующей рассылки", **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        permissions = [
            ("set_active", "Can set is_active"),
        ]


class Try(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name="рассылка")
    last_try = models.DateTimeField(auto_now_add=True, verbose_name="последняя попытка", **NULLABLE)
    server_response = models.CharField(verbose_name="ответ сервера", **NULLABLE)
    status = models.BooleanField(verbose_name="статус", **NULLABLE)

    def __str__(self):
        str = f'{self.mailing} {self.last_try} '
        if self.status:
            str += ' успешно отправилось'
        else:
            str += f' ошибка: {self.server_response}'
        return str

    class Meta:
        verbose_name = "Попытка"
        verbose_name_plural = "Попытки"

main/forms.py
from django import forms
from django.forms import BooleanField

from main.models import Mailing, Client, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ['owner', ]


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ['owner', ]


class MailingManagerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ['is_active', ]


class SuperUserMailingForm(StyleFormMixin, forms.ModelForm):
    clients = forms.ModelMultipleChoiceField(label="Клиенты",
                                             queryset=Client.objects.all(),
                                             widget=forms.CheckboxSelectMultiple(
                                                 attrs={'class': 'form-check-input'}
                                             ))

    class Meta:
        model = Mailing
        fields = ['name',
                  'message',
                  'date_time',
                  'period',
                  'status',
                  'clients',
                  'start',
                  'finish',
                  'is_active',
                  'next_sending_time']

main/views.py
import random
from main.services import get_cached_mailing_ammount, get_cached_mailing_active, get_cached_clients_ammount, \
    get_cached_blog_list

from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView

from main.forms import ClientForm, MessageForm, SuperUserMailingForm, MailingManagerForm, StyleFormMixin
from main.models import Mailing, Client, Message, Try


# Create your views here.

class HomePageView(ListView):
    model = Mailing
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mailings_ammount'] = get_cached_mailing_ammount()
        context_data['active_mailings_ammount'] = get_cached_mailing_active()
        context_data['clients_ammount'] = get_cached_clients_ammount()
        blog_list = get_cached_blog_list()
        random.shuffle(blog_list)
        context_data['blog_list'] = blog_list[:3]
        return context_data


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing


def get_default_mailing_form(user):
    class MailingForm(StyleFormMixin, forms.ModelForm):
        clients = forms.ModelMultipleChoiceField(label="Клиенты",
                                                 queryset=Client.objects.filter(owner=user),
                                                 widget=forms.CheckboxSelectMultiple(
                                                     attrs={'class': 'form-check-input'}
                                                 ))

        class Meta:
            model = Mailing
            fields = ('name', 'message', 'start', 'finish', 'period', 'clients')

    return MailingForm


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    success_url = reverse_lazy('main:mailings')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return get_default_mailing_form(user)
        if user.is_superuser:
            return SuperUserMailingForm
        if user.has_perm('main.set_active'):
            return MailingManagerForm
        raise PermissionError


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('main:mailings')


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    success_url = reverse_lazy('main:mailings')

    def get_form_class(self):
        return get_default_mailing_form(self.request.user)

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        context = self.get_context_data()

        return super().form_valid(form)


class MessageListView(LoginRequiredMixin, ListView):
    model = Message


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('main:messages')


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('main:messages')


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('main:messages')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        context = self.get_context_data()

        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    model = Client


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('main:clients')


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('main:clients')


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('main:clients')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        context = self.get_context_data()

        return super().form_valid(form)


class TryListView(LoginRequiredMixin, ListView):
    model = Try

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Рассылки</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'main/includes/inc_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылки</h1>
    <p class="lead">Рассылки - удобный сервис рассылок</p>
</div>
<div class="container">
    {% block content %}
    {% endblock %}
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            Рассылки
            <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
        </div>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

main/templates/main/client_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
  <div class="col-12">
    <div class="row">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <p>Хотите удалить клиента "{{object.full_name}}"?</p>
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'main:clients' %}" class="btn btn-outline-primary">Отмена</a>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

main/templates/main/client_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{object.full_name}}</h1>
</div>
<div class="row text-start">
    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Email</td>
                        <td>{{object.email}}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="card">
            <div class="card-header">Комментарий</div>
            {% if object.comment %}
            <div class="card-body">{{object.comment}}</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="row">
    <div class="col-12">
        <form method="post" action="" class="form-floating" enctype="multipart/form-data">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            {% if object %}
                                Редактирование
                            {% else %}
                                Создание Клиента
                            {% endif %}
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                            {% if object %}
                              Сохранить
                            {% else %}
                              Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-left">
    <h1 class="display-4">Клиенты</h1>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'main:client_create' %}">Добавить Клиента</a>
</div>
<div class="row text-center">
    {% for object in object_list %}
    {% if object.owner == user or perms.main.set_active %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.full_name }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Email: {{ object.email }}</li>
                    </ul>
                    <a href="{% url 'main:client_detail' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Посмотреть</a>
                    {% if object.owner == user %}
                    <a href="{% url 'main:client_update' object.pk %}" class="btn btn-lg btn-block btn-primary">Изменить</a>
                    <a href="{% url 'main:client_delete' object.pk %}" class="btn btn-lg btn-block btn-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load filters %}
{% block content %}
<div class="row text-center">
    <div class="col-4">
        <div class="card mb-4">
            <div class="card-header">
                <h5>Количество рассылок:</h5>
            </div>
            <div class="card-body">{{ mailings_ammount }}</div>
        </div>
    </div>
    <div class="col-4">
        <div class="card mb-4">
            <div class="card-header">
                <h5>Количество активных рассылок:</h5>
            </div>
            <div class="card-body">{{ active_mailings_ammount }}</div>
        </div>
    </div>
    <div class="col-4">
        <div class="card mb-4">
            <div class="card-header">
                <h5>Количество клиентов:</h5>
            </div>
            <div class="card-body">{{ clients_ammount }}</div>
        </div>
    </div>
</div>
<div class="row text-center">
    {% for blog in blog_list %}
        <div class="col-md-4">
            <img src="{{blog.image|my_media}}"
                     width="350"
                     height="350">
            <div class="card mb-4 box-shadow">
                <div class="card-header">{{blog.title}}</div>
            </div>
            <a href="{% url 'blogs:blog_detail' blog.pk %}" class="btn btn-lg btn-block btn-outline-primary">Почитать</a>
        </div>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/mailing_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
  <div class="col-12">
    <div class="row">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <p>Хотите удалить рассылку "{{object.name}}"?</p>
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'main:mailings' %}" class="btn btn-outline-primary">Отмена</a>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

main/templates/main/mailing_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{object.name}}</h1>
</div>
<div class="row text-start">
    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Сообщение</td>
                        <td>
                            <a href="{% url 'main:message_detail' object.message.pk %}">{{object.message}}</a>
                        </td>
                    </tr>
                    <tr>
                        <td class="w-25">Периодичность</td>
                        <td>{{ object.period }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Статус</td>
                        <td>{{ object.status }}</td>
                    </tr>
                </table>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">Клиенты:
                    {% for client in object.clients.all %}
                        <li>
                            {{ client }}
                        </li>
                    {% endfor %}
                    </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/mailing_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="row">
    <div class="col-12">
        <form method="post" action="" class="form-floating" enctype="multipart/form-data">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            {% if object %}
                                Редактирование
                            {% else %}
                                Создание рассылки
                            {% endif %}
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                            {% if object %}
                              Сохранить
                            {% else %}
                              Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/mailing_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'main:mailing_create' %}">Добавить Рассылку</a>
</div>
<div class="row text-center">
    {% for object in object_list %}
    {% if object.owner == user or perms.main.set_active %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Сообщение: {{ object.message }}</li>
                        <li>Периодичность: {{ object.period }}</li>
                        <li>Статус: {{ object.status }}</li>
                        <li>
                            Статус модерации: {% if object.is_active %} Активно {% else %} Ожидает модерации {% endif %}
                        </li>
                    </ul>
                    <a href="{% url 'main:mailing_detail' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Посмотреть</a>
                    <a href="{% url 'main:mailing_update' object.pk %}" class="btn btn-lg btn-block btn-primary">Изменить</a>
                    <a href="{% url 'main:mailing_delete' object.pk %}" class="btn btn-lg btn-block btn-danger">Удалить</a>
                </div>
            </div>
        </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

main/templates/main/message_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
  <div class="col-12">
    <div class="row">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <p>Хотите удалить Сообщение "{{object.header}}"?</p>
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'main:messages' %}" class="btn btn-outline-primary">Отмена</a>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

main/templates/main/message_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Заголовок: {{object.header}}</h1>
</div>
<div class="row text-start">
    <div class="col-12">
        <div class="card">
            <div class="card-header">Сообщение</div>
            <div class="card-body">{{object.body}}</div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/message_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="row">
    <div class="col-12">
        <form method="post" action="" class="form-floating" enctype="multipart/form-data">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            {% if object %}
                                Редактирование
                            {% else %}
                                Создание Сообщения
                            {% endif %}
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                            {% if object %}
                              Сохранить
                            {% else %}
                              Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/message_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-left">
    <h1 class="display-4">Сообщения</h1>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'main:message_create' %}">Добавить Сообщение</a>
</div>
<div class="row text-center">
    {% for object in object_list %}
    {% if object.owner == user or perms.main.set_active %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal"></h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Заголовок: {{ object.header }}</li>
                    </ul>
                    <a href="{% url 'main:message_detail' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Посмотреть</a>
                    {% if object.owner == user %}
                    <a href="{% url 'main:message_update' object.pk %}" class="btn btn-lg btn-block btn-primary">Изменить</a>
                    <a href="{% url 'main:message_delete' object.pk %}" class="btn btn-lg btn-block btn-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}